### ISSUE TITLE
Hey, I made another version of a badge bot, can you check it out please ?

### ISSUE THREAD

**Issue by Siropalafraise** [pipermatt/badgebot#1]
Hey,

I made my own version of the badge bot and updated it with some of your features.
It should be displayed on my profile. Make sure you read my ReadMe as there are some new features.

Can you install it and give me a honest opinion about it ?
Can you also tell me how to contact you outside of this "Issues" tab. I am not familiar with Github at all and I don't know how to contact you outside of this tab...

Thank you very much and have a nice day,
Siropalafraise#3862
K:30 X:535 Y:471

**Comment by pipermatt** [comment]
It's a solid addition... I had thought about making the same change but hadn't gotten around to it yet. Nicely done!

Cheers,
Dugaan#3216
K:98 X:452 Y:506
K:43 X:436 Y:503
